### ISSUE TITLE
Execution limits would be very helpful

### ISSUE THREAD

**Issue by fake-name** [hao-lee/Graphvizer#1]
Basically, I'm working on a graph with ~2000 nodes and ~3000 edges.

Feeding this to graphvis natively makes it completely poop itself. `dot.exe` spun using all of a core for about 10 minutes before I killed it.

Right now, every time I save the file in the editor, it re-spawns dot.

It'd be nice if there was a way to say "if dot takes more then *n* seconds, just kill it".

**Comment by hao-lee** [comment]
I didn't take into account the graph could be so large. Thanks for your report. I will fix it soon.

**Comment by fake-name** [comment]
Yeah, it's a really, *really* silly problem.

In this case, it's a dependency graph generated by [pyinstaller](https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#build-time-dependency-graph).

I'm not sure what I'm trying to accomplish by actually graphing it, other then my own amusement, but hey, I figured I'd comment.

**Comment by hao-lee** [comment]
Though people are not very likely to write a large file by hand, this condition is still worth considering. I find even though I set a timeout limit for the dot rendering, the syntax checking will still get stuck for a few seconds. I will move the syntax checking to a new separated thread. These work need some time, so I will release a new version in this weekend :smirk: .

**Comment by hao-lee** [comment]
DONE!
A new release is available and you can upgrade your plugin.
The default timeout is `6` seconds, you can [configure it](https://github.com/hao-lee/Graphvizer#set-timeout-for-dot-command) as needed.

**Comment by fake-name** [comment]
Cool!
