### ISSUE TITLE
Does not work on windows 10

### ISSUE THREAD

**Issue by qo4on** [hao-lee/Graphvizer#13]
1. cmd dot -V shows 2.38 version.
2. Graphvizer installed manually.
3. Syntax is set to Graphviz (DOT).

> Graphvizer -> Open Rendered Image
 is not availiable.

> Graphvizer -> Show Graphvizer Panel
shows empty window.

![image](https://user-images.githubusercontent.com/35609308/64599618-22fbd380-d3d3-11e9-80b6-c3ce9593c632.png)

**Comment by hao-lee** [comment]
Hi, Ctrl+` should have reported some errors.

**Comment by qo4on** [comment]
Thank you. I fixed some errors but Graphvizer still doesn't work.
![image](https://user-images.githubusercontent.com/35609308/64601715-e16d2780-d3d6-11e9-8c5a-c9ab3dceb131.png)

Ctrl+` shows:

> DPI mode: per-monitor v2
> startup, version: 3207 windows x64 channel: stable
> executable: /C/Program Files/Sublime Text 3/sublime_text.exe
> working dir: /C/Users/Axin/Desktop
> packages path: /C/Users/Axin/AppData/Roaming/Sublime Text 3/Packages
> state path: /C/Users/Axin/AppData/Roaming/Sublime Text 3/Local
> zip path: /C/Program Files/Sublime Text 3/Packages
> zip path: /C/Users/Axin/AppData/Roaming/Sublime Text 3/Installed Packages
> ignored_packages: []
> pre session restore time: 0.0827648
> startup time: 0.123765
> first paint time: 0.124765
> reloading plugin Default.arithmetic
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.colors
> reloading plugin Default.comment
> reloading plugin Default.convert_color_scheme
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.detect_indentation
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.rename
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.ui
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin ShellScript.ShellScript
> reloading plugin Vintage.vintage
> reloading plugin Vintage.vintage_commands
> reloading plugin Vintage.vintage_motions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.01-pygments
> reloading plugin 0_package_control_loader.50-backrefs
> reloading plugin 0_package_control_loader.50-enum
> reloading plugin 0_package_control_loader.50-markupsafe
> reloading plugin 0_package_control_loader.50-pymdownx
> reloading plugin 0_package_control_loader.50-python-markdown
> reloading plugin 0_package_control_loader.50-pyyaml
> reloading plugin 0_package_control_loader.50-typing
> reloading plugin 0_package_control_loader.51-python-jinja2
> reloading plugin 0_package_control_loader.55-mdpopups
> reloading plugin BracketHighlighter.bh_core
> reloading plugin BracketHighlighter.bh_logging
> reloading plugin BracketHighlighter.bh_plugin
> reloading plugin BracketHighlighter.bh_popup
> reloading plugin BracketHighlighter.bh_regions
> reloading plugin BracketHighlighter.bh_remove
> reloading plugin BracketHighlighter.bh_rules
> reloading plugin BracketHighlighter.bh_search
> reloading plugin BracketHighlighter.bh_swapping
> reloading plugin BracketHighlighter.bh_wrapping
> reloading plugin BracketHighlighter.support
> reloading plugin ColorSchemeEditor.ColorSchemeEditor-ST2
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> reloading plugin Package Control.Package Control
> reloading plugin PackageResourceViewer.package_resource_viewer
> reloading plugin PackageResourceViewer.package_resources
> reloading plugin Graphvizer-master.graphvizer
> reloading plugin Graphvizer-master.graphvizer_panel
> reloading plugin Graphvizer-master.syntaxchecker
> plugins loaded
> Package Control: Skipping automatic upgrade, last run at 2019-09-10 13:35:15, next run at 2019-09-10 14:35:15 or after
> decode image failed

**Comment by hao-lee** [comment]
Sublime don't trigger `file open event` during startup. If the image was not generated before you restart sublime, it won't be generated during startup either. You can try to edit this file and see if the image generated. If some errors happens, Ctrl+` or Ctrl+Shift+X will show some error messages.

**Comment by qo4on** [comment]
You are right, when I've changed the code I see the image. But there is a small rendering bug: dashed line on the bottom and on the right. I found this image in `C:\Users\Axin\AppData\Local\Temp\1.png` and that image was absolutely fine, no dashed lines.

![Untitled-1](https://user-images.githubusercontent.com/35609308/64604489-af11f900-d3db-11e9-9ab1-79041f86fba6.png)

**Comment by hao-lee** [comment]
:sweat_smile:  This is really strange. Maybe this is a bug of Sublime. I haven't encounter this.
