### ISSUE TITLE
Navigating in image

### ISSUE THREAD

**Issue by qo4on** [hao-lee/Graphvizer#14]
It would be nice to navigate from one part of the graph to another holding left mouse button (like in Photoshop `space` button) and zoom-in zoom-out holding right mouse button (like in Photoshop `z` button). Using SVG would be more useful for zooming instead of PNG.

**Comment by hao-lee** [comment]
Yes, this feature would be really useful, but [Sublime haven't support this yet](https://forum.sublimetext.com/t/sublime-text-image-viewer/33961/2). I also think Sublime should implement Zoom-In and Zoom-Out functionality. You can use other image viewer which can auto refresh when the image changed.

**Comment by qo4on** [comment]
Thanks, can you suggest which image viewer I can use with Graphvzer? Your Graphvzer shows more precise image than similar plugin for Atom.

**Comment by hao-lee** [comment]
You can use FastStone which is able to reload image automatically when the image is changed. It's a powerful image viewer.

**Comment by qo4on** [comment]
But it is external program, how can I integrate it with sublime I didn't find any plugin for that? Or you mean with every image manually open this image in viewer?

**Comment by hao-lee** [comment]
Sublime didn't provide full support for image viewing, so plugin can't solve this problem and only Sublime can do this. If you use external program to view image, you need to open every image manually. For now, there is no better way. :pensive:

**Comment by qo4on** [comment]
Do you know another image viewer with auto refresh? FastStone is not very convenient. I tried JPEGView and Sumatra but they are not refreshing even when refresh is set to true in settings.

**Comment by hao-lee** [comment]
Sorry, I haven't tried other image viewers. Maybe you can write a simple viewer using python.[`watchdog`](https://pypi.org/project/watchdog/) module can be used to monitor file changes and using [`matplotlib`](https://pypi.org/project/matplotlib/) module to show image.

**Comment by qo4on** [comment]
Ok, thanks.
