### ISSUE TITLE
Feature Request: Display Custom Images

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [hao-lee/Graphvizer#16]
Hi,

Thank you so much for this wonderful plugin! :-)

I have a feature request, that hopefully would add value.

Would it be possible to also render custom images?  I think the screen shot below describe it best, but at a high level, I have some custom images I like to use for nodes, and it would be helpful if they also rendered in the previewer.

```
digraph G {

    compound = true;

    label = "Machine Architecture";
    labelloc = "t";
    fontsize = 30;

    {
        node [shape=box];
        Machine0 [label = "", penwidth=0, shapefile="pc.png", width=0.5, height=0.5, fixedsize="true"];
        MachineX [label = "MachineX"];
        MachineY [label = "MachineY"];
    }

    {
        rank = same;
        MachineX MachineY;
    }

   Machine0 -> MachineX -> MachineY;

}
``` 

---

---

## Previewer
![image](https://user-images.githubusercontent.com/6528788/73573056-66b5af00-4440-11ea-91de-dbac2ef2c189.png)

---

---

## dot -Tpng dummy-file.dot -o sample-diagram.png
![image](https://user-images.githubusercontent.com/6528788/73573084-78975200-4440-11ea-8759-edcf48d0e6be.png)

**Comment by hao-lee** [comment]
Hi,
I didn't know this usage before :sweat_smile: . This feature is indeed useful. It seems that I just need to adjust the current working directory of dot command. I will fix it soon. Thanks!

**Comment by hao-lee** [comment]
Hi, this issue has been fixed and it inspires me to implement [another two features](https://github.com/hao-lee/Graphvizer#specifying-layout-engine). Thanks. :smirk: You can upgrade to 3.0.0 now.
