### ISSUE TITLE
v3 is not live

### ISSUE THREAD

**Issue by michaelblyons** [hao-lee/Graphvizer#17]
Did you forget to `git push --tags`, or are you still getting more stuff ready? 😉

**Comment by hao-lee** [comment]
:smile: Hi, 3.0.0 has more features. I'm eager to release too, but before this, I still need to test it more carefully because the whole codebase is refactored. If everything is OK, I will push the v3.0.0 tag today or tomorrow.

**Comment by michaelblyons** [comment]
Haha, no problem. I'm just excited.

**Comment by michaelblyons** [comment]
I don't know if you knew this, but ~since v3211 (released 2019-10-01),~ [there is now a "Build System"](https://github.com/sublimehq/Packages/pull/1889) for Graphviz. _[**Edit:** Sorry, only the Beta got the improvements]_

- <kbd>Ctrl</kbd>+<kbd>B</kbd> to render a `png` image with `dot` in the same folder.
    - On MacOS, use <kbd>Cmd</kbd> as usual.
- <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd> to choose `svg` output or to use a different engine (`neato`, `twopi`, etc.).
- Reports any syntax errors in the build output, and double-click navigates to the error location.


It's not as good as your awesome plugin, but it may help people with less demanding needs.

**Comment by hao-lee** [comment]
Thanks. I didn't know it before because my v3211 version doesn't have this graphviz build system by default and I have to add it manually from your pull request. It's indeed lightweight and easy to use. It seems you are also a Graphviz enthusiast. :smirk: I never thought one can create a build system for Graphviz. This is really a new direction.

**Comment by michaelblyons** [comment]
> Thanks. I didn't know it before because my v3211 version doesn't have this graphviz build system by default and I have to add it manually from your pull request.

Oh no! I just looked for the next release after the PR was merged. I didn't know that the code didn't make it into that release. 😬 Sorry about that!

**Comment by hao-lee** [comment]
Hello, 3.0.0 has been released.

By the way, I find that it's very difficult to manage a large graph source file because dot language doesn't support variable definition. If I want to change some attribute values, I have to do a global replacing which is very bored and easy to make mistakes. [A straightforward solution](https://stackoverflow.com/a/30343185/4112667) is use M4 macro preprocessor. So my next plan is to integrate GNU M4 Macro Syntax to extend the default dot grammar. This should be interesting.

**Comment by michaelblyons** [comment]
That is indeed interesting. May I recommend that you make it a syntax file here in this repository? Use a root scope of something like `embedding.graphviz.m4`, then put in your macro syntax, and `- include: scope:source.graphviz`.

(I am away from my computer and can't check the actual scope names right now.)

There are actually at least four different ways to arrange things to include the M4 syntax, but this is probably the best if it works. I can outline the others when I have a chance.

**Comment by michaelblyons** [comment]
Here are the four methods, with their good and bad attributes:

## Change the builtin Graphviz package

This is opening a PR at `sublimehq/Packages` with changes to add M4.

### Pros

- All the code is in one place.
- Least effort required.

### Cons

- The PR has maybe 30% chance of being accepted, because
- The builtin syntax is shared by lots of people, many of whom do not use the same macro system, and some of whom may use a conflicting macro syntax

## Build your own Graphviz syntax

This is making a self-contained syntax file here in this repository that does not refer to the builtin package in any way.

### Pros

- All of _your_ code is in one place.
- No need for PRs---you can merge improvements immediately.

### Cons

- Any improvements to the builtin package have to be added here, separately.
- Any improvements here are not available to the builtin packages.

## (simple) Linked syntax

This is what I suggested above: You make a small syntax package that only defines the entry points for M4 and includes the `main` context of the builtin package.

### Pros

- Any change to the builtin repository is immediately mirrored to all of your package's users
- The Graphviz syntax is centralized.
- If someone else has a macro system that they like, they can do the same thing without worrying if the macro syntax conflicts.

### Cons

- Places that embed wrapped Graphviz syntax (e.g. a loop) will include the main syntax scope, which might not be relevant in the place that the loop happens.


## Complex Linked syntax

This is similar to the previous example, but instead of `- include: scope:source.dot`, you append specific subscopes, like `- include: scope:source.dot#brackets`. There is not a lot of complexity in the Graphviz syntax definition right now, but someone may change that someday. :wink: If you are interested in improving the builtin syntax definition to make it closer to the spec, we'd love to have your help!

### Pros

- (Same as previous)

### Cons

- Chopping up a syntax definition and reconstituting it can be tedious

**Comment by hao-lee** [comment]
Many thanks. This is really helpful. I'm not familiar with syntax definition, so it's impossible for me without your help to consider these aspects so detailed. I always think your avatar is familiar, but I don't remember where I saw it until I open the contributor list of Sublime Text syntax. I am already eager to implement new features, but for now, I have to learn some basic knowledge. Thanks again for your detailed explanation. :smile:

**Comment by hao-lee** [comment]
Graphviz is extremely awesome. I prefer it to any other graph tool. I even want to create a tutorial repository to help other people learn it. :smirk:
