### ISSUE TITLE
Use the side-by-side settings editor

### ISSUE THREAD

**Issue by michaelblyons** [hao-lee/Graphvizer#20]
Instead of separate links in the Menu for "Settings - Default" and "Settings - User," do this:

https://github.com/jfcherng/Sublime-OpenUri/blob/55c301b7f4f9b19d412cbd1b0e13a3aa017bbc8c/menus/Main.sublime-menu#L28-L33

I am not sure about doing it for Keymap, though. I think Keymap is global.

**Comment by hao-lee** [comment]
Really helpful! Thanks! This way is more intuitive.

**Comment by hao-lee** [comment]
After searching on GitHub, I find keymap also supports this way. See [here](https://github.com/sjunaidinfoxhcange/SXML/blob/df273c90d653d1d40caf51bd18f872cef504badc/Main.sublime-menu#L45-L46).
