### ISSUE TITLE
 UTF8 text is not supported?

### ISSUE THREAD

**Issue by JoseHZBY** [hao-lee/Graphvizer#21]
It seems that UTF8 text is not supported.

```graphviz
graph {
	图
}
```
and the error in console:
>[2020-03-24 11:56:51] - Lexical Error: line 2, column 1: token recognition error at: '图'

**Comment by hao-lee** [comment]
You are right. The lexer currently doesn't recognize the non-ASCII characters. I will add UTF-8 support soon.

**Comment by JoseHZBY** [comment]
that will be cool, thank you.

**Comment by hao-lee** [comment]
Node name supports Chinese characters now.
