### ISSUE TITLE
ST4 "Go to Definition" and Theme Selection Disabled when Plugin Installed

### ISSUE THREAD

**Issue by yodaldevoid** [hao-lee/Graphvizer#24]
When Graphvizer is installed on Sublime Text 4, indexing fails to find any symbols in any file disabling "Go to Definition" and for some reason theme selection in the menu is also greyed out.

**Comment by hao-lee** [comment]
Could you paste the console output using Ctrl+`. Thanks.

**Comment by nzgrover** [comment]
I'm having similar issues, "Go to definition" doesn't work and when right-clicking on a folder "Find in Folder..." is greyed out when Graphvizer is loaded. Adding Graphvizer to my Ignored Packages immediately fixes the issues. I don't see anything relevant when I press ctrl+`

Is there anything else I could do or try to help out? I love the package, it's been very helpful to me.

**Comment by hao-lee** [comment]
@nzgrover Hi, I upgrade my Sublime and can reproduce this bug now. This is a severe problem. I will fix it this weekend. Thanks for reporting this again.

**Comment by hao-lee** [comment]
This problem is very strange because eventlisteners can't be triggered. I have posted a question on Sublime Text forum. Hope we can solve this problem this week :sweat_smile:

**Comment by hao-lee** [comment]
I have found the root cause but can't understand why...  I need to post another question to the forum...

**Comment by hao-lee** [comment]
This is a bug of Sublime Text 4. See [here](https://forum.sublimetext.com/t/defining-windowcommand-will-grey-out-many-menuitems/59412/5?u=haolee). I hope there is a workaround.

**Comment by hao-lee** [comment]
Fixed using a workaround.

**Comment by nzgrover** [comment]
Nice one! A fix is a fix.

**Comment by michaelblyons** [comment]
If you're relying on things in Packages/User, that's not a workaround... it's the intended solution.

**Comment by hao-lee** [comment]
> If you're relying on things in Packages/User, that's not a workaround... it's the intended solution.

Hi, @michaelblyons Sorry, I couldn't understand this. What is `relying on things in Packages/User`... Thanks.
