### ISSUE TITLE
Image not displaying when viewing HTML document in Chrome

### ISSUE THREAD

**Issue by NWDMarketing** [hao-lee/Graphvizer#25]
Hi there 

I am very new to HTML (have only been learning for a day or so) I watched a youtube tutorial and followed every step but the result is not the same so I guess I need someone who know a lot more about HTML than me to have a look.
![Screenshot 2021-10-11 at 22 14 06](https://user-images.githubusercontent.com/92338442/136856311-af364089-685b-4c67-b196-12c928d0f67b.png)
.
See the screen shot attached, all i am trying to do is place an image in a table row but each time input the attached code I just get the 'loading image' icon rather than the image itself: please help.

**Comment by hao-lee** [comment]
Hello, maybe you can ask your question on stackoverflow. I'm not familiar with HTML either. This issue is not related to Graphvizer project, so I will close it. You can still comment on this thread if you have other questions. Thanks.
