### ISSUE TITLE
'dot' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Adarma** [hao-lee/Graphvizer#27]
I don't have the dot.exe location in my path, so I set the setting `dot_cmd_path` to the full path of dot.exe.

```
{
	"dot_cmd_path": "C:\\Graphviz\\bin\\dot.exe"
}
```

When I build, it seems the path from settings is not used. It is just calling `dot`.

Output:
```
'dot' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 57ms with exit code 1]
[shell_cmd: dot "C:\Whatever\TheName.dot" -O -Tpng]
```

Sublime Text 4166
Windows 10

**Comment by Adarma** [comment]
It seems to _sometimes_ work now 😕
Noticed this in the console:

```
Unable to open /C/Users/xxx/AppData/Roaming/Sublime Text/Packages/Graphvizer/Graphvizer.sublime-settings
```

I only just updated to Sublime Text 4166 today. Maybe related...

**Comment by michaelblyons** [comment]
Did you already have this package installed, and it worked until the upgrade? Or you installed the package since 4166?

**Comment by Adarma** [comment]
I already had it installed

**Comment by hao-lee** [comment]
@Adarma Sorry for the delay. What if you run C:\\Graphviz\\bin\\dot.exe on windows cmd? Will it be executed normally?

**Comment by Adarma** [comment]
Yes, running that cmd works fine now and also worked at the time I raised this issue.
It seems the problem has gone now somehow.
Maybe just close this issue if you can't reproduce it.

**Comment by hao-lee** [comment]
> Yes, running that cmd works fine now and also worked at the time I raised this issue. It seems the problem has gone now somehow. Maybe just close this issue if you can't reproduce it.

feel free to report if encounter problems again 😏
