### ISSUE TITLE
win10下使用，无法渲染图片

### ISSUE THREAD

**Issue by fivedoumi** [hao-lee/Graphvizer#3]
如图所示。

![loading image](https://user-images.githubusercontent.com/6835605/41158588-0a51ef44-6b5c-11e8-9396-817f3486be71.png)

**Comment by hao-lee** [comment]
如果要添加注释的话还是推荐用Graphviz 官方文档里面的注释语法，也就是 `/*   */` 和 `//`，和 C 语言一样。不过，`#` 开头的行应该也会被忽略才对，但是从图中看是第 8 行报告了词法错误，说明插件的词法分析部分有问题，没有正确的将第 8 行忽略掉。我粗略看了下，如果在第 8 行回车一下错误就消失了，即只要 `#` 行不是最后一行就可以了。我基本知道错在哪了，目测这两天就能发个新版本，敬请期待！

**Comment by hao-lee** [comment]
[v1.5.0](https://github.com/hao-lee/Graphvizer/releases/tag/v1.5.0) 已经修复完成了，在 Sublime 内使用 Package Control 升级插件即可。

---

[v1.5.0](https://github.com/hao-lee/Graphvizer/releases/tag/v1.5.0) has fixed this problem. Please upgrade this plugin in Sublime using Package Control.

**Comment by fivedoumi** [comment]
![image](https://user-images.githubusercontent.com/6835605/41222051-8b3d7ad6-6d98-11e8-991e-28a40f6fb190.png)

我这还是渲染不了，已然提示 Loading images...

**Comment by hao-lee** [comment]
这就奇怪了，打开控制台看看有没有什么报错吧，快捷键是 Ctrl + `（Esc下方的波浪号键）

**Comment by fivedoumi** [comment]
![image](https://user-images.githubusercontent.com/6835605/41224417-04c9534c-6d9f-11e8-8fa0-29276a6376b2.png)

console没报错信息，然后我去png image的生成路径去 查看，没找到graphviz.png 文件，只找到graphviz.dot。

![image](https://user-images.githubusercontent.com/6835605/41224485-2f2da570-6d9f-11e8-8656-8758eb9c29a5.png)

**Comment by fivedoumi** [comment]
看起来是 .png文件没成功生成，sublime无法载入。

**Comment by hao-lee** [comment]
这就很奇怪了，`dot` 命令的路径有没有配置正确啊。在 `cmd` 里用命令 `dot xxx.dot -Tpng -o out.png` 试试能不能生成图片。没有错误却又生成不了图片这就很诡异了。

**Comment by fivedoumi** [comment]
![image](https://user-images.githubusercontent.com/6835605/41228844-5d83e6a2-6dac-11e8-984c-65bb8d2cb114.png)
是可以生成的，确实很诡异。

**Comment by hao-lee** [comment]
我在另一台Win7上试了下没问题，这应该跟平台无关，毕竟Linux和Mac都没问题。你再试试编辑文件比如随便敲几个空格触发下图片生成。

**Comment by fivedoumi** [comment]
这个我也试过，没有效果。
我是win10.

**Comment by fivedoumi** [comment]
今天发现 atom下的graphviz插件更好用。。。。转到atom 了

**Comment by hao-lee** [comment]
好吧，atom那个没法自动刷新吧

**Comment by fivedoumi** [comment]
有的，可以试试渲染。
而且语法高亮，自动提示，错误检查， 也很便捷。

**Comment by hao-lee** [comment]
还有自动提示？怎么提示的，是IDE那种代码补全吗

**Comment by fivedoumi** [comment]
对啊，自动补全，你可以试试看。
graphviz-preview-plus ，language-dot 这两个atom插件。

**Comment by hao-lee** [comment]
如果只是单词补全的话，Sublime 也可以装插件。如果是语义补全直接能提示出node或edge的属性列表的话那就很高级了。

**Comment by hao-lee** [comment]
Issue 我先关闭了 :sweat_smile: ，另一个已解决 Issue 里面有人用 Win10 测过了，可以用，我觉得平台不应该是问题，以后还需要帮助的话再打开~

**Comment by pinghe** [comment]
建议，当保存时或自动保存时才刷新图片

**Comment by hao-lee** [comment]
@pinghe 这样似乎不太方便啊，不过可以提供一个选项来根据个人需要进行如此配置

**Comment by pinghe** [comment]
谢谢。

当图很复杂的这种场景下，在保存时更新很有用

**Comment by hao-lee** [comment]
@pinghe 已添加功能，关闭实时渲染后，图片只有在保存文件时更新，详情参见主页 README

**Comment by pinghe** [comment]
多谢

**Comment by pinghe** [comment]
如果dot文件还未命名，则默认在image_dir 目录下生成graphviz.png，如果一旦命名了，则生成的文件名，建议和dot文件名一致。这样多文件同时编辑时不会混淆

**Comment by pinghe** [comment]
另外，更新配置项后，不能实时生效，需要重启sublimetext

**Comment by hao-lee** [comment]
> 如果dot文件还未命名，则默认在image_dir 目录下生成graphviz.png，如果一旦命名了，则生成的文件名，建议和dot文件名一致。这样多文件同时编辑时不会混淆

问题已经新建 Issue 追踪 #11

**Comment by hao-lee** [comment]
> 另外，更新配置项后，不能实时生效，需要重启sublimetext

问题已经新建 Issue 追踪 #12
