### ISSUE TITLE
Saving the image

### ISSUE THREAD

**Issue by Kuluulu** [hao-lee/Graphvizer#5]
Hi,

I don't know if I am just blind but I would really enjoy being able to __set where the resulting image is saved__.
I am having problems running my dot script in the Terminal. But Sublime + Graphvizer work perfectly, so it would be great to not have to deal with the tmp-directory or the Terminal but just save it where I need it.

Thank you for the great package!

**Comment by hao-lee** [comment]
Hi, this is a good feature. Thanks for your advice. I will implement it this week. :smirk:

**Comment by Kuluulu** [comment]
Awesome! Thank you, looking forward to it!

**Comment by hao-lee** [comment]
Done! The manual is [here](https://github.com/hao-lee/Graphvizer#change-the-image-directory).
