### ISSUE TITLE
Queue being overflowed on frequent changes in source

### ISSUE THREAD

**Issue by Vanderhoof** [hao-lee/Graphvizer#7]
Hello!
Thank you for great package, it's very convenient and really saves a lot of time for me!

There's one problem though: if you make a lot of frequent changes the rendering queue is being overflowed because package tends to render EACH of the intermediate changes. You can easily simulate this issue by adding a node with label and starting furiously clapping on random keys adding symbols to label. At some moment sublime text starts responding very slowly (see attached gif). I can live with ST being a bit slow but if the diagram is big, it just freezes and I have to restart it.

I've provided a simple solution below. Adding these two lines of code we tell rendering thread to only process the most recent change, skipping all the intermediate ones (which is exactly what we expect from it). It works for me, ST no longer freezes.

I don't mind if you find another solution, it's the solving of the issue what I am concerned about.

Thank you!

![gr](https://user-images.githubusercontent.com/12543857/50415896-ac13b000-082e-11e9-98bb-c3c2ec4185d3.gif)

Same situation after this fix applied:

![gr2](https://user-images.githubusercontent.com/12543857/50416150-1d079780-0830-11e9-9c20-e27fd8b49bc2.gif)

Solution:

```python
def dot_thread(self):
	while True:
		while self.queue_rendering.qsize() > 1:  # added line 1
			self.queue_rendering.get()  # added line 2
		contents = self.queue_rendering.get(block=True, timeout=None)
```

**Comment by hao-lee** [comment]
Hi, thanks for your contribution. This is indeed a problem. I  didn't think about this condition before. I will merge your solution in the next release. Thanks!
