### ISSUE TITLE
Support PlantUML

### ISSUE THREAD

**Issue by pinghe** [hao-lee/Graphvizer#9]
It would really great if we could have direct support for `PlantUML`.

````
@startuml
@enduml
````

http://plantuml.com/zh/

**Comment by hao-lee** [comment]
PlantUML can only be used with JRE environment which is very inconvenient to be included in this plugin. Another ways is use [PlantUML server](http://www.plantuml.com/plantuml/) and let the plugin work as a client. Neither of these methods is elegance, so, for now, I have no plan to add this feature or create a PlantUML plugin. I would close this issue and will reopen it if I find a better to implement it. Thanks for your suggestion.
